### ISSUE TITLE
아이템 4. 관련 질문드립니다.

### ISSUE THREAD

**Issue by DDAMDOO** [BacknPacker/effective_java#10]
정적 메소드와 정적 필드만 담은 클래스는 객체지향적이지 않다고 하는부분에 대해서 질문이 있습니다.

그 이유가 컴파일러에서 기본 생성자를 생성하여 다른 클래스에서 인스턴스 생성이 가능해서 라고 내용을 본 것 같은데 정확히 이해가 되지 않아서요.

어떠한 문제점이 있는지 설명해주실 수 있을까요?

**Comment by quedevel** [comment]
@DDAMDOO 
'정적 메소드와 정적 필드만 담은 클래스는 **객체지향적**이지 않다'

**객체지향적**이란것은 결국 데이터를 추상화하여 객체를 만들고 그 객체간들의 상호작용을 하도록하는 프로그래밍인데
Util 클래스와 같이 여러 클래스에서 공통적으로 사용되는 메서드들 끼리 모아 만든 클래스입니다.

극단적인 예시를 들자면
```
public class Calculator {
    private Calculator(){}
    public static int plus(int x , int y){ return x+y; }
    public static int minus(int x , int y){ return x-y; }
    public static int multiply(int x , int y){ return x*y; }
    public static int divide(int x , int y){ return x/y; }

    public static void main(String[] args) {
        Calculator.plus(1,1);
        Calculator.minus(1,1);
        Calculator.multiply(1,1);
        Calculator.divide(1,1);
    }
}
```
위 클래스는 오직 계산을 하기 위해 설계된 클래스이기 때문에 다른 역할을 하면 안되는것 입니다.
private생성자로 객체 생성을 막았기 때문에 상속도 할 수 없습니다.
객체를 생성할 수 없어서 다른 객체들과의 상호작용은 불가하기 때문에 객체지향적이라곤 할 수 없으나 **확실한 역할을 갖고 설계된 클래스**입니다.


하지만 만약 위 처럼 private 생성자를 만들지 않는다면
**public Calculator(){}** 가 자동 생성이 되기 때문에 상속도 가능하며 다른 클래스에 구현 컴포지트 모든게 가능하면서
결국엔 설계된 의도와 아주아주 많이 다른 클래스로 변모가 될 가능성이 있기 때문에 사전에 예방이 필요합니다

**Comment by DDAMDOO** [comment]
아하 네네 예시를 보니 조금 더 이해하기 쉽네요 설명 감사합니다!
