### ISSUE TITLE
아이템 25 질문

### ISSUE THREAD

**Issue by DDAMDOO** [BacknPacker/effective_java#24]
공부하면서 보다보니 jdk11에서는 책에 나온 컴파일 방식인 javac Main.java Dessert.java로 컴파일하면 컴파일오류가 안난다고 하는 것 같은데 그 이유를 아시는 분 있나요?

https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224

이 블로그 내용입니다.

**Comment by quedevel** [comment]
저는  javac Main.java Dessert.java 해도 컴파일 오류가 안나길래 뭔가 했더니 제가 jdk11을 쓰고있어서 그랬군요....ㅎ

이펙티브 자바가 jdk8을 기준으로 작성되어있기에 jdk9, jdk10, jdk11 릴리즈 노트들을 확인해봤습니다.

정확하진 않지만 의심가는 내용은 jdk10 릴리즈 노트에 

The descriptions on this Release Note page might also identify potential compatibility issues that you could encounter when migrating to JDK 10. The [Kinds of Compatibility](https://wiki.openjdk.java.net/display/csr/Kinds+of+Compatibility) page on the OpenJDK wiki identifies three types of potential compatibility issues for Java programs used in these descriptions:

Source: Source compatibility concerns translating Java source code into class files.

Binary: Binary compatibility is defined in The Java Language Specification as preserving the ability to link without error.

Behavioral: Behavioral compatibility includes the semantics of the code that is executed at runtime.

이러한 내용이 있었습니다. 아닐수도 있지만 확인한번 해보시는게 ㅎㅎ

**Comment by lee-ji-hoon** [comment]
@DDAMDOO 
jdk11 부터는 중첩클래스들이 접근지정자에 상관없이 서로의 필드에 접근이 가능해졌기 때문에 오류가 안나는 것으로 저는 이해가 됐습니다.

좀 더 자세한 내용은 jdk11 버전 릴리즈 노트의 `Nest-Based Access Control` 를 검색해보시는 것도 좋을 것 같습니다!

[OpenJDK - Nest-Based Access Control](http://openjdk.java.net/jeps/181) 
[사용법 및 관련된 내용](https://www.studytonight.com/java-11/nestbased-access-control-in-java-11)

**Comment by DDAMDOO** [comment]
앗 두분 다 좋은 정보 감사합니다! 확인해봐야겠네요 ㅎㅎ
