### ISSUE TITLE
아이템 28. 배열보다는 리스트를 사용하라.

### ISSUE THREAD

**Issue by lee-ji-hoon** [BacknPacker/effective_java#29]
### 📖  p165. ~ 이를 허용한다면 컴파일러가 자동 생성한 형변환 코드에서 런타임에 ClassCastException이 발생할 수 있다. 

여기에서 런타임에 `ClassCastException` 이 발생하는 일을 막아주겠다는 제네릭 타입 시스템의 취지에 어긋나는 것이다.   
라는 말이 헷갈려서 이해한 내용이 맞는지 한 번 확인해주시면 감사하겠습니다.

- [ ] 배열은 `런타임` 에서 에러를 체크하며, 제네릭은 `컴파일` 타임에서 체크한다.
- [ ] 하지만 제네릭은 컴파일 타입에서 체크 하기 때문에 `ClassCastException` 이 발생해서는 안된다.

> 위 내용을 토대로 이해해보자면 제네릭 배열을 사용할 경우 `ClassCastException` 이 발생할 수도 있는데,     
> 이는 `런타임 에러` 이므로 제네릭 타입 시스템의 사용취지에 벗어난다. 

이렇게 이해했는데 맞을까요?

<hr/>

### ❓ 개인적인 질문
배열보다는 리스트 즉 제네릭타입을 사용하는 것이  더 안전하기 때문이라는 이유로 이해했습니다.   
> 런타임이 아닌 컴파일 시점에서 에러를 잡아주기 때문

- [ ] 협업 진행하면서 코드 구현 할 때 배열 보다 리스트를 실제로도 많이 사용하는지
  - 만약 그렇다면 LIst는 빈 엘리먼트를 허락하지 않는데, 그런 경우 어떻게 해결하시는지 궁금합니다.

**Comment by quedevel** [comment]
1. 네 맞습니다. 일단 제네릭을 만든 취지가 매번 `형변환`을 해야하는 번거로움 + `런타임 에러`에 있기 때문입니다.
`컴파일 에러`는 빌드 자체가 되지 않기 때문에 개발자가 바로 확인하고 수정할 수 있지만
`런타임 에러`는 이미 빌드해서 서버 배포 후 운영 중인데 언제 어느 시점에 사용해서 시스템에 오류가 발생할지 예상할 수 없기 때문이라 생각합니다.

2. 실무에서도 배열보다는 리스트를 많이 사용합니다. 
하지만 라이브러리의 리턴값이 배열로 주는 것도 많기 때문에 사용을 안하는것은 아닙니다.
특별하게 빈 엘리먼트까지 고려하면서 작업을 해본 적은 없는 것 같습니다.

**Comment by lee-ji-hoon** [comment]
@quedevel 

넵 질문에 답변해주셔 감사합니다.

> **만약 그렇다면 LIst는 빈 엘리먼트를 허락하지 않는데, 그런 경우 어떻게 해결하시는지 궁금합니다.**

위 내용은 저도 토이프로젝트 했던 코드들을 보니 배열을 아예 쓴 적이 없고 HashMap / List 등을 썼다는 것을 느꼈습니다.  
최근에 알고리즘을 공부하다보니 순간적으로 `실무에서는 어떻게 해결하는 것일까?` 라는 생각이 들었는데 뭔가 당연한 내용들이었던 것 같네요! 

답변해주셔서 감사합니다
