### ISSUE TITLE
아이템 44. 표준 함수형 인터페이스를 사용하라.

### ISSUE THREAD

**Issue by lee-ji-hoon** [BacknPacker/effective_java#39]
### p263
1. `LinkedHashMap`의 proteced 메서드인 `removeEldestEntry`를 재정의 하면 캐시로 사용할 수 있다.  
> 해당 메서드 한 번 볼려고 했는데 `LinkedHashMap`에서 보이지가 않던데 혹시 찾으신분 계실까요?  

2.  `removeEldsEntry`가 인스턴스 메서드**라서** 가능한 방식이다  

> **인스턴스 메서드라서**  가능하다 라고 읽히는 부분이 반대로 클래스 메서드인 경우에는 불가능하다? 라는 생각이 들었습니다.   
> 그런데 그럴 이유가 도저히 생각이 안나서 혹시 이해가 되신분 있으시면 알고 싶습니다!..

**Comment by quedevel** [comment]
@lee-ji-hoon 

1. 저는 일단 `LinkedHashMap.java`를 들어가니 보이긴합니다.
```java
protected boolean removeEldestEntry(Map.Entry<K,V> eldest) {
    return false;
}
```

2. `removeEldestEntry`가 인스턴스 메서드라서 가능한 방식이다.
일단 `LinkedHashMap`이 `HashMap`을 상속받은 클래스이며 특징이

* HashMap.java
```java
// Callbacks to allow LinkedHashMap post-actions
void afterNodeAccess(Node<K,V> p) { }
void afterNodeInsertion(boolean evict) { }
void afterNodeRemoval(Node<K,V> p) { }
```
위 처럼 `HashMap`에 `put`이나 `merge` 등 동작을 할 때 callback으로 돌리는 함수를 인스턴스 메서드로 정의 해뒀습니다. <br>
`put`이나 `merge` 이러한 동작들은 인스턴스 메서드로 만들 수 박에 없고 안에서 콜백을 돌려야 하니 콜백 함수들도 <br>
모두 인스턴스 메서드로 작성이 되었습니다.

<br>

* LinkedHashMap.java
```java
  /**
   * HashMap.Node subclass for normal LinkedHashMap entries.
   */
  static class Entry<K,V> extends HashMap.Node<K,V> {
      Entry<K,V> before, after;
      Entry(int hash, K key, V value, Node<K,V> next) {
          super(hash, key, value, next);
      }
  }

  /**
   * The head (eldest) of the doubly linked list.
   */
  transient LinkedHashMap.Entry<K,V> head;

  /**
   * The tail (youngest) of the doubly linked list.
   */
  transient LinkedHashMap.Entry<K,V> tail;
  
  void afterNodeInsertion(boolean evict) { // possibly remove eldest
      LinkedHashMap.Entry<K,V> first;
      if (evict && (first = head) != null && removeEldestEntry(first)) {
          K key = first.key;
          removeNode(hash(key), key, null, false, true);
      }
  }
```
`HashMap`을 상속받은 `LinkedHashMap`에선 `afterNodeInsertion`인스턴스 함수를 오버라이드 했기 때문에<br>
결론적으로 인스턴스 메서드 내부에서는 static 함수를 사용할 수 없습니다. 따라서 `removeEldestEntry`함수는 <br>
오직 인스턴스 메서드이기 때문에 사용이 가능한걸로 확인됩니다.

**Comment by lee-ji-hoon** [comment]
@quedevel 

1. 인텔리제이에서 검색할때 그냥 `removeE` 까지만 치고 검색했을 때는 안뜨는데 `removeEldestEntry` 전체로 검색하니 저도 보이네요   뭔가 신기하네요 찾아주셔서 감사합니다

2. 아아 제가 순간적으로 잘못생각하고 있었습니다. 인스턴스 변수 스태틱 변수를 생각하고 있었는데 메서드니까 애초에 불가능한게 맞고 한 번 더 로직을 보니 확실해졌네요 감사합니다.
